name: CD-CI Jhoana

on:
  push:
    branches:  
      -  "main"
      -  "develop"
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v4

      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - name: Install dependencies
      run: npm install

    - name: Run unit and integration test
      run: npm run test

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Clear action cache
        uses: actions/cache@v2
        with:
          path: ~/.github/actions
          key: ${{ runner.os }}-actions-${{ hashFiles('**/action.yml') }}
          run: rm -rf ${{ inputs.path }}
      

      - name: Login to Docker Hub
        uses: docker/login-actions@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ESTE API-POC=LASTEST

  