name: CD-CI Jhoana

on:
  push:
    branches:  [main, develop, feature/azure, feature/Slack]
  pull_request:
    branches: [main, develop, feature/azure, feature/Slack]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v4

      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - name: Install dependencies
      run: npm install

    - name: Run unit and integration test
      run: npm run test

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/final_work1.3:latest

  deploys:
    runs-on: ubuntu-lastest 
    needs: build

    steps:
      - name: Checkout
        uses: action/checkout@4

      - name: Login  Azure
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
    
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} 
          image: ${{ secrets.DOCKERHUB_USERNAME }}/final_work1.3:latest

  CI_CD_success_notification:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Notify success on Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Jhoana Coronel'